load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

new_local_repository(
    name = "cmakeProjectLib",
    path = "../cmakeProjectLib",
    build_file = "@//:bazelLibs/BUILD.cmakeProjectLib",
)

git_repository(
    name = "googletest",
    remote = "https://github.com/google/googletest",
    tag = "release-1.10.0",
)
