load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_local_repository(
    name = "libPackageA",
    path = "../LibPackageA",
    build_file = "BUILD.libPackageA",
)

new_git_repository(
    name = "googletest",
    build_file = "@//:BUILD.gtest",
    remote = "https://github.com/google/googletest",
    tag = "release-1.10.0",
)