load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

new_local_repository(
    name = "libPackageA",
    path = "../PhysicsLib",
    build_file = "@//:bazelLibs/BUILD.libPackageA",
)

git_repository(
    name = "googletest",
    remote = "https://github.com/google/googletest",
    tag = "release-1.10.0",
)
